'use strict';
const MODULES = [
  { id: 'm01', icon: '☁️',  title: 'Cloud Fundamentals',         tags: ['Altro', 'Well-Architected'],                   cards: typeof MODULE01 !== 'undefined' ? MODULE01 : [] },
  { id: 'm02', icon: '🔐',  title: 'IAM & Shared Responsibility', tags: ['IAM', 'Shared Responsibility'],                cards: typeof MODULE02 !== 'undefined' ? MODULE02 : [] },
  { id: 'm03', icon: '💻',  title: 'EC2 & Compute',               tags: ['EC2'],                                         cards: typeof MODULE03 !== 'undefined' ? MODULE03 : [] },
  { id: 'm04', icon: '🗄️',  title: 'S3 & Storage',                tags: ['S3', 'Storage'],                               cards: typeof MODULE04 !== 'undefined' ? MODULE04 : [] },
  { id: 'm05', icon: '🌐',  title: 'VPC & Networking',            tags: ['VPC', 'Networking', 'Route 53', 'CloudFront'], cards: typeof MODULE05 !== 'undefined' ? MODULE05 : [] },
  { id: 'm06', icon: '🗃️',  title: 'Database',                    tags: ['RDS', 'DynamoDB'],                             cards: typeof MODULE06 !== 'undefined' ? MODULE06 : [] },
  { id: 'm07', icon: '⚡',  title: 'Serverless & Container',      tags: ['Lambda', 'ECS / Fargate', 'EKS'],              cards: typeof MODULE07 !== 'undefined' ? MODULE07 : [] },
  { id: 'm08', icon: '📨',  title: 'Messaging & Integration',     tags: ['SNS', 'SQS'],                                  cards: typeof MODULE08 !== 'undefined' ? MODULE08 : [] },
  { id: 'm09', icon: '📊',  title: 'Monitoring & Management',     tags: ['CloudWatch', 'CloudFormation', 'Support'],     cards: typeof MODULE09 !== 'undefined' ? MODULE09 : [] },
  { id: 'm10', icon: '🔒',  title: 'Security',                    tags: ['Security'],                                    cards: typeof MODULE10 !== 'undefined' ? MODULE10 : [] },
  { id: 'm11', icon: '📈',  title: 'Analytics & AI/ML',           tags: ['Analytics', 'AI / ML'],                        cards: typeof MODULE11 !== 'undefined' ? MODULE11 : [] },
  { id: 'm12', icon: '💰',  title: 'Billing & Pricing',           tags: ['Billing & Cost'],                              cards: typeof MODULE12 !== 'undefined' ? MODULE12 : [] },
  { id: 'm13', icon: '🏛️',  title: 'Well-Architected & CAF',      tags: ['Well-Architected'],                            cards: typeof MODULE13 !== 'undefined' ? MODULE13 : [] },
  { id: 'm14', icon: '🚚',  title: 'Migrazione & Disaster Recovery', tags: ['Altro'], bankSkip: 50,                     cards: typeof MODULE14 !== 'undefined' ? MODULE14 : [] },
  { id: 'm15', icon: '🛡️',  title: 'Identità & Sicurezza Avanzata', tags: ['Security', 'IAM'], bankSkip: 25,            cards: typeof MODULE15 !== 'undefined' ? MODULE15 : [] },
  { id: 'm16', icon: '🛠️',  title: 'Strumenti & Governance',      tags: ['CloudFormation', 'CloudWatch'], bankSkip: 25,  cards: typeof MODULE16 !== 'undefined' ? MODULE16 : [] },
  { id: 'm17', icon: '🧭',  title: 'Mappa dei Servizi',           tags: ['Storage', 'Networking', 'Analytics', 'AI / ML'], bankSkip: 25, cards: typeof MODULE17 !== 'undefined' ? MODULE17 : [] },
  { id: 'm18', icon: '🧾',  title: 'Costi Avanzati & Supporto',   tags: ['Billing & Cost', 'Support'], bankSkip: 25,     cards: typeof MODULE18 !== 'undefined' ? MODULE18 : [] },
];
